services:
  - type: web
    name: ai-cloze-generator
    env: node
    plan: free
    buildCommand: npm install --prefix client && npm install --prefix server && npm run build --prefix client
    startCommand: npm start --prefix server
    autoDeploy: true
