import { ArrowLeft, LockKeyhole, Pill, Search } from "lucide-react";
import { useEffect, useMemo, useState } from "react";
import type { User } from "@supabase/supabase-js";
import type { Drug } from "../types/drug";
import type { DataRoute } from "../utils/dataRoutes";
import { drugPath } from "../utils/dataRoutes";
import { getPublishedDrugBySlug, listPublishedDrugPreviews } from "../services/drugDatabaseService";
import { listDrugRecommendationRelations, recommendationLocationPreview, resolveRecommendationLocations } from "../services/knowledgeRelationService";
import ProtectedContentGate from "./ProtectedContentGate";
import RecommendationLink, { type RecommendationLinkLocation } from "./RecommendationLink";
import SharedSelect from "./SharedSelect";

type DrugRoute = Extract<DataRoute, { tab: "drugs" }>;
type DrugPreview = Pick<Drug, "id" | "slug" | "genericName" | "titleVi" | "drugClass" | "specialties" | "status" | "publishedAt">;
interface Props { route: DrugRoute; user: User | null; onNavigate: (path: string) => void }

const sections: Array<{ key: keyof Drug; label: string }> = [
  { key: "mechanism", label: "Cơ chế" }, { key: "indications", label: "Chỉ định" }, { key: "dosing", label: "Liều dùng" }, { key: "renalAdjustment", label: "Điều chỉnh suy thận" }, { key: "hepaticAdjustment", label: "Điều chỉnh suy gan" }, { key: "contraindications", label: "Chống chỉ định" }, { key: "adverseEffects", label: "Tác dụng phụ" }, { key: "interactions", label: "Tương tác" }, { key: "monitoring", label: "Theo dõi" }, { key: "pregnancy", label: "Thai kỳ" }, { key: "breastfeeding", label: "Cho con bú" },
];
function errorText(error: unknown) { return error instanceof Error ? error.message : "Không thể tải dữ liệu thuốc."; }

export default function DrugDataPage({ route, user, onNavigate }: Props) {
  return route.kind === "drug-detail" ? <DrugDetailRoute slug={route.slug} user={user} onNavigate={onNavigate} /> : <DrugCatalog user={user} onNavigate={onNavigate} />;
}

function DrugCatalog({ user, onNavigate }: { user: User | null; onNavigate: (path: string) => void }) {
  const [items, setItems] = useState<Array<Drug | DrugPreview>>([]); const [query, setQuery] = useState(""); const [drugClass, setDrugClass] = useState("all"); const [specialty, setSpecialty] = useState("all"); const [loading, setLoading] = useState(true); const [error, setError] = useState("");
  useEffect(() => { let active = true; setLoading(true); void listPublishedDrugPreviews().then((records) => { if (active) { setItems(records); setError(""); } }).catch((reason) => { if (active) setError(errorText(reason)); }).finally(() => { if (active) setLoading(false); }); return () => { active = false; }; }, []);
  const options = useMemo(() => ({ classes: [...new Set(items.map((item) => item.drugClass).filter(Boolean))], specialties: [...new Set(items.flatMap((item) => item.specialties || []).filter(Boolean))] }), [items]);
  const filtered = useMemo(() => { const needle = query.trim().toLocaleLowerCase(); return items.filter((item) => (!needle || `${item.titleVi} ${item.genericName} ${item.drugClass}`.toLocaleLowerCase().includes(needle)) && (drugClass === "all" || item.drugClass === drugClass) && (specialty === "all" || item.specialties.includes(specialty))); }, [items, query, drugClass, specialty]);
  return <section className="mode-panel mx-auto w-full max-w-[1600px] px-4 py-6 sm:px-6 xl:px-8" aria-labelledby="drugs-title"><div className="glass-panel border border-teal-100 bg-white/75 p-5 sm:p-7"><div className="flex items-start gap-3"><span className="flex h-11 w-11 shrink-0 items-center justify-center rounded-2xl bg-teal-100 text-teal-700"><Pill size={23} /></span><div><p className="text-xs font-extrabold uppercase tracking-[.14em] text-teal-600">Kho dữ liệu trung tâm</p><h1 id="drugs-title" className="mt-1 text-2xl font-extrabold text-rose-950">Thuốc</h1><p className="mt-1 text-sm text-slate-500">Danh mục thuốc và nội dung chi tiết đã được xuất bản.</p></div></div><div className="mt-5 grid gap-3 md:grid-cols-[minmax(0,1fr)_220px_220px]"><label className="relative"><Search className="absolute left-3 top-1/2 -translate-y-1/2 text-slate-400" size={17} /><input value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Tìm theo tên, hoạt chất, nhóm..." className="h-11 w-full rounded-xl border border-slate-200 bg-white pl-10 pr-3 text-sm outline-none focus:border-teal-300" /></label><SharedSelect value={drugClass} onValueChange={setDrugClass} ariaLabel="Lọc nhóm thuốc" options={[{ value: "all", label: "Tất cả nhóm thuốc" }, ...options.classes.map((item) => ({ value: item, label: item }))]} searchable /><SharedSelect value={specialty} onValueChange={setSpecialty} ariaLabel="Lọc chuyên khoa" options={[{ value: "all", label: "Tất cả chuyên khoa" }, ...options.specialties.map((item) => ({ value: item, label: item }))]} searchable /></div>{error && <p role="alert" className="mt-4 rounded-xl border border-rose-200 bg-rose-50 px-3 py-2 text-sm font-semibold text-rose-700">{error}</p>}{loading ? <Loading /> : <div className="mt-5 grid gap-3 sm:grid-cols-2 lg:grid-cols-3">{filtered.map((item) => <button key={item.id} type="button" onClick={() => onNavigate(drugPath(item.slug))} className="rounded-2xl border border-slate-200 bg-white/85 p-4 text-left transition hover:-translate-y-0.5 hover:border-teal-300 hover:shadow-md"><div className="flex items-center gap-3"><span className="flex h-10 w-10 shrink-0 items-center justify-center rounded-xl bg-teal-50 text-teal-700"><Pill size={19} /></span><div className="min-w-0"><h2 className="truncate font-extrabold text-slate-800">{item.titleVi}</h2><p className="text-xs font-semibold text-slate-400">{item.genericName}</p></div></div><p className="mt-3 text-sm font-semibold text-slate-500">{item.drugClass || "Chưa phân nhóm"}</p>{!user && <p className="mt-3 inline-flex items-center gap-1 text-xs font-bold text-violet-700"><LockKeyhole size={13} />Đăng nhập để xem chi tiết</p>}</button>)}{filtered.length === 0 && <Empty text="Không tìm thấy thuốc phù hợp." />}</div>}</div></section>;
}

function DrugDetailRoute({ slug, user, onNavigate }: { slug: string; user: User | null; onNavigate: (path: string) => void }) {
  const [drug, setDrug] = useState<Drug | null>(null); const [links, setLinks] = useState<RecommendationLinkLocation[]>([]); const [loading, setLoading] = useState(Boolean(user)); const [error, setError] = useState("");
  useEffect(() => { let active = true; if (!user) return; setLoading(true); void getPublishedDrugBySlug(slug).then(async (record) => { if (!record) { if (active) setError("Nội dung không còn khả dụng."); return; } const relations = await listDrugRecommendationRelations(record.id); const locations = await resolveRecommendationLocations(relations.map((item) => item.recommendation_id)); if (active) { setDrug(record); setLinks(locations.filter((item) => item.publicEligible).map(recommendationLocationPreview)); } }).catch((reason) => { if (active) setError(errorText(reason)); }).finally(() => { if (active) setLoading(false); }); return () => { active = false; }; }, [slug, user]);
  if (!user) return <ProtectedContentGate />;
  if (loading) return <Loading />;
  if (!drug) return <section className="mode-panel mx-auto max-w-3xl px-4 py-8 text-center"><p className="text-sm font-semibold text-slate-500">{error || "Không tìm thấy thuốc."}</p><button type="button" onClick={() => onNavigate("/thuoc")} className="mt-4 font-bold text-teal-700">Quay về danh sách</button></section>;
  return <section className="mode-panel mx-auto w-full max-w-[1400px] px-4 py-6 sm:px-6 xl:px-8"><div className="glass-panel border border-teal-100 bg-white/75 p-5 sm:p-7"><button type="button" onClick={() => onNavigate("/thuoc")} className="inline-flex items-center gap-2 text-sm font-bold text-teal-700"><ArrowLeft size={16} />Danh sách thuốc</button><div className="mt-5 flex items-start gap-3"><span className="flex h-12 w-12 shrink-0 items-center justify-center rounded-2xl bg-teal-100 text-teal-700"><Pill size={24} /></span><div><p className="text-xs font-extrabold uppercase tracking-[.14em] text-teal-600">Hồ sơ thuốc</p><h1 className="mt-1 text-2xl font-extrabold text-rose-950">{drug.titleVi}</h1><p className="text-sm font-semibold text-slate-500">{drug.genericName}</p></div></div><div className="mt-5 grid gap-4 md:grid-cols-2"><Info label="Tên khác" value={[...drug.aliases, ...drug.brandNames].join(", ")} /><Info label="Nhóm thuốc" value={drug.drugClass} /><Info label="Chuyên khoa" value={drug.specialties.join(", ")} /><Info label="Tóm tắt" value={drug.summary} />{sections.map((item) => <Info key={item.key} label={item.label} value={String(drug[item.key] || "")} />)}</div><section className="mt-5 rounded-2xl border border-violet-100 bg-white/80 p-4"><h2 className="text-sm font-extrabold text-slate-700">Khuyến cáo liên quan</h2>{links.length ? <div className="mt-3 grid gap-2">{links.map((item) => <RecommendationLink key={item.recommendationId} location={item} onNavigate={onNavigate} />)}</div> : <p className="mt-2 text-sm font-semibold text-slate-400">Chưa có dữ liệu liên kết công khai.</p>}</section></div></section>;
}

function Info({ label, value }: { label: string; value: string }) { return <section className="rounded-2xl border border-slate-200 bg-white/80 p-4"><h2 className="text-sm font-extrabold text-slate-700">{label}</h2><p className="mt-2 whitespace-pre-wrap text-sm leading-6 text-slate-600">{value || "Chưa có dữ liệu."}</p></section>; }
function Empty({ text }: { text: string }) { return <p className="rounded-2xl border border-dashed border-slate-200 p-8 text-center text-sm text-slate-500 sm:col-span-2 lg:col-span-3">{text}</p>; }
function Loading() { return <p className="mx-auto mt-6 max-w-4xl rounded-xl border border-dashed border-slate-200 p-8 text-center text-sm font-semibold text-slate-500">Đang tải dữ liệu...</p>; }
