import type { CalculatorDefinition } from "./types";

const now = "2026-01-01T00:00:00.000Z";

export const calculatorDefinitions: CalculatorDefinition[] = [
  {
    id: "bmi",
    slug: "bmi",
    name: "Body Mass Index",
    nameVi: "Chỉ số khối cơ thể",
    shortName: "BMI",
    specialty: "Nội tổng quát",
    category: "Đánh giá cơ bản",
    description: "Tính BMI từ cân nặng và chiều cao.",
    purpose: "Sàng lọc nhanh tình trạng cân nặng ở người trưởng thành.",
    whenToUse: ["Đánh giá ban đầu theo cân nặng và chiều cao."],
    whenNotToUse: ["Không dùng đơn độc để đánh giá thành phần cơ thể hoặc chẩn đoán."],
    limitations: ["Cần diễn giải theo tuổi, giới, thai kỳ và bối cảnh lâm sàng."],
    inputFields: [
      { id: "weightKg", label: "Cân nặng", type: "number", unit: "kg", required: true, min: 1, max: 500, step: 0.1, helpText: "Nhập cân nặng theo kg." },
      { id: "heightCm", label: "Chiều cao", type: "number", unit: "cm", required: true, min: 30, max: 250, step: 0.1, helpText: "Nhập chiều cao theo cm." },
    ],
    calculation: { handlerId: "bmi" },
    resultDefinitions: [
      { key: "underweight", label: "Thiếu cân", description: "BMI dưới 18,5.", max: 18.49, severity: "moderate" },
      { key: "normal", label: "Bình thường", description: "BMI từ 18,5 đến dưới 25.", min: 18.5, max: 24.99, severity: "neutral" },
      { key: "overweight", label: "Thừa cân", description: "BMI từ 25 đến dưới 30.", min: 25, max: 29.99, severity: "moderate" },
      { key: "obesity", label: "Béo phì", description: "BMI từ 30 trở lên.", min: 30, severity: "high" },
    ],
    interpretations: [], guidelineReferences: [], drugReferences: [], flashcardReferences: [], quizReferences: [], relatedCalculatorReferences: [],
    references: ["https://www.who.int/data/gho/data/themes/topics/topic-details/GHO/body-mass-index"],
    status: "published", version: "1.0.0", sourceVerified: true, createdAt: now, updatedAt: now,
  },
  {
    id: "cockcroft-gault",
    slug: "cockcroft-gault",
    name: "Cockcroft-Gault Creatinine Clearance",
    nameVi: "Độ thanh thải creatinine Cockcroft-Gault",
    shortName: "CrCl",
    specialty: "Thận",
    category: "Chức năng thận",
    description: "Ước tính độ thanh thải creatinine theo Cockcroft-Gault.",
    purpose: "Hỗ trợ ước tính CrCl để đối chiếu chỉ định và chỉnh liều khi phù hợp.",
    whenToUse: ["Khi cần ước tính CrCl theo công thức Cockcroft-Gault."],
    whenNotToUse: ["Không thay thế đánh giá chức năng thận đầy đủ hoặc hướng dẫn thuốc cụ thể."],
    limitations: ["Cân nặng sử dụng trong công thức cần được chọn theo bối cảnh lâm sàng."],
    inputFields: [
      { id: "age", label: "Tuổi", type: "number", unit: "năm", required: true, min: 1, max: 120, step: 1 },
      { id: "sex", label: "Giới tính sinh học", type: "select", required: true, options: [{ value: "male", label: "Nam" }, { value: "female", label: "Nữ" }] },
      { id: "weightKg", label: "Cân nặng", type: "number", unit: "kg", required: true, min: 1, max: 500, step: 0.1 },
      { id: "creatinineMgDl", label: "Creatinine huyết thanh", type: "number", unit: "mg/dL", required: true, min: 0.01, max: 30, step: 0.01 },
    ],
    calculation: { handlerId: "cockcroft-gault" },
    resultDefinitions: [{ key: "calculated", label: "CrCl ước tính", description: "Kết quả tính theo Cockcroft-Gault.", severity: "neutral" }],
    interpretations: [], guidelineReferences: [], drugReferences: [], flashcardReferences: [], quizReferences: [], relatedCalculatorReferences: [],
    references: ["https://pubmed.ncbi.nlm.nih.gov/4830801/"],
    status: "published", version: "1.0.0", sourceVerified: true, createdAt: now, updatedAt: now,
  },
  {
    id: "curb-65",
    slug: "curb-65",
    name: "CURB-65 Score",
    nameVi: "Thang điểm CURB-65",
    shortName: "CURB-65",
    specialty: "Hô hấp",
    category: "Viêm phổi",
    description: "Đánh giá mức độ nặng viêm phổi cộng đồng bằng 5 tiêu chí.",
    purpose: "Hỗ trợ phân tầng nguy cơ trong bối cảnh viêm phổi cộng đồng.",
    whenToUse: ["Khi đã đánh giá người bệnh nghi viêm phổi cộng đồng."],
    whenNotToUse: ["Không dùng thay cho đánh giá lâm sàng, bệnh kèm hoặc nhu cầu chăm sóc."],
    limitations: ["Cần đối chiếu hướng dẫn địa phương và toàn trạng người bệnh."],
    inputFields: [
      { id: "confusion", label: "Lú lẫn mới xuất hiện", type: "boolean", required: true, options: [{ value: "false", label: "Không · 0" }, { value: "true", label: "Có · 1" }] },
      { id: "ureaMmolL", label: "Ure >7 mmol/L", type: "boolean", required: true, options: [{ value: "false", label: "Không · 0" }, { value: "true", label: "Có · 1" }] },
      { id: "respiratoryRate", label: "Nhịp thở ≥30", type: "boolean", required: true, options: [{ value: "false", label: "Không · 0" }, { value: "true", label: "Có · 1" }] },
      { id: "lowBloodPressure", label: "Huyết áp thấp", type: "boolean", required: true, options: [{ value: "false", label: "Không · 0" }, { value: "true", label: "Có · 1" }] },
      { id: "age65", label: "Tuổi ≥65", type: "boolean", required: true, options: [{ value: "false", label: "Không · 0" }, { value: "true", label: "Có · 1" }] },
    ],
    calculation: { handlerId: "curb-65" },
    resultDefinitions: [
      { key: "low", label: "Nguy cơ thấp", description: "Điểm thấp cần được đặt trong bối cảnh lâm sàng.", max: 1, severity: "low" },
      { key: "moderate", label: "Nguy cơ trung gian", description: "Cần đánh giá thêm tình trạng người bệnh.", min: 2, max: 3, severity: "moderate" },
      { key: "high", label: "Nguy cơ cao", description: "Cần đánh giá mức độ nặng và nơi điều trị theo hướng dẫn.", min: 4, severity: "high" },
    ],
    interpretations: [], guidelineReferences: [], drugReferences: [], flashcardReferences: [], quizReferences: [], relatedCalculatorReferences: [],
    references: ["https://pubmed.ncbi.nlm.nih.gov/14630421/"],
    status: "published", version: "1.0.0", sourceVerified: true, createdAt: now, updatedAt: now,
  },
];
